name: bot status API updater

on:
  schedule:
  - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.10 

      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"

      - name: Run updater script
        env:
          APP_ID: ${{ secrets.APP_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOTS: ${{ secrets.BOTS }}
          SESSION: ${{ secrets.SESSION }}
          API_KEY: ${{ secrets.API_KEY }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          
        run: python main.py