name: bot status API updater

on:
  workflow_dispatch: {} # Allow manually kicking off builds
  schedule:
  - cron: "0 0 * * MON"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        uses: py-actions/py-dependency-install@v2
        with:
          path: "requirements.txt"

      - name: Run updater script
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION: ${{ secrets.SESSION }}
          ENDPOINT_API_KEY: ${{ secrets.ENDPOINT_API_KEY }}
          GET_ENDPOINT: ${{ secrets.GET_ENDPOINT }}
          UPDATE_ENDPOINT: ${{ secrets.UPDATE_ENDPOINT }}
          OOTU_ENDPOINT: ${{ secrets.OOTU_ENDPOINT }}
          CHECK_TIMEOUT: ${{ secrets.CHECK_TIMEOUT }}
          DELAY_TIMEOUT: ${{ secrets.DELAY_TIMEOUT }}

        run: python main.py
